square/Cleanse

Cleanse/ScopedBindingDecorator.swift

I tried to use Cleanse from master branch, but it gave me compilation error.

Fix ScopedBindingDecorator conformation to BindingBuilder

---

Cleanse/LegacyObjectGraph.swift
Cleanse/Provider.swift
Cleanse/ValidationVisitor.swift

v4 includes stronger type-safety for tuples so `(Void) -> ...` should be `() -> ...` and multi-parameter closures cannot be wrapped into tuples anymore.

Swift 4 support.

---

.travis.yml
Cleanse.xcodeproj/project.pbxproj
Cleanse.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
Cleanse/CanonicalRepresentable.swift

The `ImplicitlyUnwrappedOptional` type was removed in swift v4.2 (https://github.com/apple/swift-evolution/blob/master/proposals/0212-compiler-version-directive.md).

Swift 4.2 Support.

---

Cleanse.podspec
Cleanse/Scope.swift

This is provided for convenience and the consumer isn't required to use this scope at all. Including this because we reference the `Singleton` scope for bindings that are shared across the entire object graph. This should help decrease confusion for new consumers learning how to set up their project.

Add default Singleton Scope.

---

Cleanse/WeakProvider.swift

The `AnyObject` requirement means we can only use it on class types and not protocol or struct types.

Remove class requirement for Weak Providers.

---

Package.swift

Xcode failes to import dependency if using the old Package.swift

Fix the Package.swift file

---

CHANGELOG.md
Cleanse.xcodeproj/project.pbxproj
Cleanse/ComponentFactory.swift
Cleanse/Graph.swift
CleanseTests/SubcomponentTests.swift
README.rst

Subcomponents today are fairly buggy. `Graph` instances that are required to construct subcomponents cause exceptions on `build(:)`. In order to fix this, we need something to retain `Graph` object instances.
This change puts the retention responsibility on `ComponentFactory`. `ComponentFactory` is now responsible for retaining all live instances of subgraphs (aka subcomponents) that it creates via the `build(:)` function. Subgraphs will be deinitialized alongside `ComponentFactory`.

Retain subcomponent graphs.

---

.gitignore
.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
.travis.yml
CHANGELOG.md
Cleanse/Factory.swift
Examples/CleanseGithubBrowser/CleanseGithubBrowser.xcodeproj/project.pbxproj
Examples/CleanseGithubBrowser/CleanseGithubBrowser.xcodeproj/xcshareddata/xcschemes/CleanseGithubBrowser.xcscheme
Examples/CleanseGithubBrowser/CleanseGithubBrowserTests/CleanseGithubBrowserTests.swift

* Exposes public `factory` function for assisted injection `Factory` class. This is similar to `Provider` and other core primitives to allow for manual testing.
* Tests for the sample project weren't being run (or built). Change travis CI config to build and test the sample project.
* Bump TravisCI to Xcode 11.2.

Xcode 11.2 Support.

---

CHANGELOG.md
Cleanse/Graph.swift

Upon a `Graph` instance's `finalize` function, we clear out the dictionary of `futureProviders`. The dictionary holds all instances of `FutureProvider`s that represent a type whose factory instance may not have been created yet. When we create the correct `Provider` instance inside our graph, it retains a strong reference to the `FutureProvider` instance, so even though we clear out the dictionary after `finalize`, these instances are still in memory as they are being retained by their equivalent `Provider` instances.
This poses an issue for `WeakProvider`s as their wrapped `Provider` instance rightfully holds onto a `weak` instance of the `FutureProvider`. Therefore, if no other `Provider` retains its equivalent `FutureProvider`, it will be deinitialized and all `WeakProvider`s for a …

Fix WeakProviders becoming deinitialized.

---

cleansec/CleansecFramework/Linking/LinkedComponent.swift
cleansec/CleansecFramework/Linking/LinkedInterface.swift
cleansec/CleansecFramework/Linking/LinkedModule.swift
cleansec/CleansecFramework/Linking/Linker.swift
cleansec/CleansecFrameworkTests/LinkerTests.swift
cleansec/cleansec.xcodeproj/project.pbxproj

Linker step is responsible for joining all the `ReferenceProvider` instances to their corresponding `DanglingProvider`. These references can be linked across different `ModuleRepresentation` instances (i.e. different Swift modules).

Implement Linker Step

---

cleansec/CleansecFramework/Cleansec.swift
cleansec/CleansecFramework/Resolver/CanonicalProvider.swift
cleansec/CleansecFramework/Resolver/ResolvedComponent.swift
cleansec/CleansecFrameworkTests/PluginTests.swift
cleansec/cleansec.xcodeproj/project.pbxproj
cleansec/cleansec/main.swift

* Plugins interact with `cleansec` via stdout and by passing the ast file as an arg.
* Adds emit option to `cleansec` for verbose logging.

Cleansec Plugin interface.

---

cleansec/CleansecFramework/Visitors/CleanseTypeVisitor.swift
cleansec/CleansecFramework/Visitors/Provider Visitor/ComponentRootProviderVisitor.swift
cleansec/CleansecFramework/Visitors/Representations/Models.swift
cleansec/CleansecFramework/Visitors/Representations/ProviderModels.swift
cleansec/script/swiftc-ast.rb

* Also fixes critical `swiftc-ast` script bug where `mkdir -p` was being applied to the basename instead of dirname.

Expose visitor publicly for plugins to reuse.

---

cleansec/CleansecFramework/Linking/Linker.swift
cleansec/CleansecFramework/Resolver/CanonicalProvider.swift
cleansec/CleansecFramework/Resolver/ResolutionError.swift
cleansec/CleansecFramework/Resolver/Resolver.swift
cleansec/CleansecFramework/Visitors/Provider Visitor/ProviderBuilders.swift
cleansec/CleansecFramework/Visitors/Provider Visitor/ProviderVisitor.swift
cleansec/CleansecFramework/Visitors/Representations/DebugData.swift
cleansec/CleansecFramework/Visitors/Representations/ProviderModels.swift
cleansec/CleansecFrameworkTests/BindingsVisitorTests.swift
cleansec/CleansecFrameworkTests/ResolverTests.swift
cleansec/cleansec.xcodeproj/project.pbxproj

* Creates new `DebugData` struct to provide additional metadata on core primitives.
* Makes the `ResolutionError` types error-rich by providing the debug data in the exception.

Plumb DebugData through pipeline.

---

cleansec/script/swiftc-ast.rb

This allows consumers who want to keep the `SWIFT_EXEC` option set, but disable the specific `dump-ast` command. Primarily helpful for temporary disabling.

Offer disable option for dump-ast script.

---

cleansec/CleansecFramework/Cleansec.swift
cleansec/CleansecFramework/Resolver/ResolutionError.swift
cleansec/CleansecFramework/Resolver/Resolver.swift
cleansec/CleansecFrameworkTests/ResolverTests.swift
cleansec/cleansec/main.swift

This improves the error output with Xcode to look like actual compilation errors that can link to the actual source locations.

Improved cleansec errors that integrate with Xcode

---

cleansec/.gitignore
cleansec/Makefile
cleansec/README.md

Makefile supports `build`, `clean`, and `release` to help automate these processes.
Updated README to help describe building, testing, adding `cleansec` to your project, and some of its internal components.

Add Makefile to cleansec and update README

---

cleansec/CleansecFramework/Visitors/Provider Visitor/ProviderBuilders.swift
cleansec/CleansecFramework/Visitors/Provider Visitor/ProviderVisitor.swift

These can be reused for plugins when attempting to parse structures similar to the default bindings.

Grant public access to CleansecFramework Visitors.

---

cleansec/CleansecFramework/Cleansec.swift
cleansec/CleansecFramework/Linking/Linker.swift
cleansec/CleansecFramework/Resolver/ResolutionError.swift
cleansec/CleansecFramework/Visitors/BindingsVisitor.swift
cleansec/CleansecFramework/Visitors/FileVisitor.swift
cleansec/CleansecFramework/Visitors/Provider Visitor/ProviderVisitor.swift
cleansec/SwiftAstParser/Regex.swift

The existing print statements are replaced with `debug` level logging via `os_log`. This will emit useful debugging info, but not pollute the usage of `cleansec` in production.

Replace print with os_log.

---

cleansec/CleansecFramework/Resolver/CanonicalProvider.swift
cleansec/CleansecFrameworkTests/ResolverTests.swift

* Tagged providers were being filtered from resolution due to bad regex patterns. This is a temporary patch, reworking how we map `CanonicalProviders` into sibling implicit, lazy, and Weak Pproviders is a better long term fix to this issue.

[cleansec] Resolve Tagged Providers bug fix.

---

cleansec/script/swiftc-ast.rb

Previously the script would exit with status code 0 which would let Xcode continue compiling. We want to fail `swiftc-ast.rb` if the normal swift compilation also fails.

Fail swiftc-ast script if compilation fails.

---

cleansec/CleansecFramework/Resolver/CanonicalProvider.swift
cleansec/CleansecFramework/Resolver/ResolutionError.swift
cleansec/CleansecFramework/Resolver/ResolvedComponent.swift
cleansec/CleansecFramework/Resolver/Resolver.swift
cleansec/CleansecFramework/Resolver/TypeKey.swift
cleansec/CleansecFrameworkTests/ResolverTests.swift
cleansec/cleansec.xcodeproj/project.pbxproj

* First improvement is adding a `TypeKey` value type to normalize types.
Cleanse has a type of one-to-many mapping for a given dependency to how it can be used within the object graph. For a given `Type`, it can be represented as `Provider<Type>`, `WeakProvider<Type>`, or `() -> Type`. Currently we support this by adding each of these types into the object graph dictionary for key lookup during dependency resolution. However, for other resolution steps (i.e duplicate binding, cyclical dependencies), we filter these types out so that we don't over-report errors or run into false-positive. The `TypeKey` helps normalize the types we see in the graph so that we don't have to unnecessarily add and filter certain types during resolution.
* Refactors resolution functions into their primary …

Refactoring improvements for Resolver.

---

cleansec/SwiftAstParser/Parsing/ASTStringHelpers.swift
cleansec/SwiftAstParser/Parsing/InputParser.swift
cleansec/SwiftAstParserTests/SanitizerTests.swift

Some `-dump-ast` outputs have an irregularity where particular nodes have incorrect indentation, thus causing to be grouped under the wrong parent. This irregularity materializes as a newline with only `n` whitespace characters that should be prepended to the following line.
This change modifies `sanitize(lines:)` to account for this possibility. Introduces a helper `flatMapScanPrevious` which allows for scanning the previous element within `flatMap`.

[cleansec] Sanitize -dump-ast spaced newlines.

---

cleansec/CleansecFramework/Cleansec.swift
cleansec/CleansecFramework/Resolver/ResolutionError.swift
cleansec/CleansecFramework/Resolver/Resolver.swift
cleansec/CleansecFrameworkTests/ResolutionErrorFormatTests.swift
cleansec/CleansecFrameworkTests/ResolverTests.swift
cleansec/cleansec.xcodeproj/project.pbxproj

* If one has a missing provider and has compiled a `Cleanse.Module` that `cleansec` parses from the search paths to include that particular provider, we will include a note below the error message with a list of suggested modules they might wish to include.
Depending on the user's search path for parsed modules, it's possible that the suggested module could be stale and not have been _actually_ compiled/updated. This will likely occur if the output path for all cleansec modules is the same. Considering this is merely a suggestion to help guide the user towards finding their module, this edge case doesn't pose too much of an issue.
* Added `ResolutionErrorFormatTests` to add coverage for the emitted error description that goes to `stderr` that Xcode parses.

Add suggested modules to "Missing Provider" errors.

---

CHANGELOG.md
Cleanse/AssistedInjection.swift
Cleanse/AssistedInjectionArities.swift
CleanseGen/main.swift
CleanseTests/AssistedInjectionTests.swift

The source location for assisted factory bindings was being set at the `file`, `line`, and `function` within the `AssistedInjectionArities.swift` file, which makes the debug information incorrect for errors such as `MissingProvider`. This change should correctly place the source location info at the site of the binding for assisted factories.

Fix Assisted Factory binding location.

---

.github/workflows/main.yml
CleanseTests/CleanseTests.swift
CleanseTests/MemoryManagementTests.swift
Examples/CleanseGithubBrowser/CleanseGithubBrowser/NetworkModule.swift

Addresses issue #171. More info about why we had to disambiguate between the 0-th arity `factory` function and the `value` function is described in the issue.

Compile Cleanse project using XC 12.
